type: segment_anything_2
name: sam2_hiera_small-r20240801
display_name: Segment Anything 2 (Small)
encoder_model_path: https://github.com/CVHub520/X-AnyLabeling/releases/download/v2.4.0/sam2_hiera_small.encoder.onnx
decoder_model_path: https://github.com/CVHub520/X-AnyLabeling/releases/download/v2.4.0/sam2_hiera_small.decoder.onnx
